# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [62]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [63]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [64]:
# Method 1
a = np.random.random((2,3,5))

In [65]:
# Method 2

In [66]:
# Method 3

#### 4. Print *a*.


In [67]:
# your code here
print(a)

[[[0.78783247 0.40898748 0.33323612 0.17844396 0.73812431]
  [0.27620709 0.12946243 0.89947759 0.24373076 0.90414391]
  [0.55585711 0.61807061 0.66423265 0.82842348 0.82924037]]

 [[0.80742628 0.93194212 0.49134654 0.92310726 0.93792914]
  [0.81802654 0.23063904 0.25591393 0.2326182  0.26363679]
  [0.59413087 0.55976807 0.52913791 0.05082046 0.01794061]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [68]:
# your code here
b = np.full((5,2,3),1)

#### 6. Print *b*.


In [69]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [70]:
# your code here
if a.size - b.size ==0:
    print("Yes, a and b have the same size")
else:
    print("They have different size")

Yes, a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [71]:
# your answer here
# no because different shapes
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [72]:
# your code here
c = np.reshape(b,(2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [73]:
# your code/answer here
# now working because both matrixes have the same shape hence enabling addition
d = np.add(a,c)
d

array([[[1.78783247, 1.40898748, 1.33323612, 1.17844396, 1.73812431],
        [1.27620709, 1.12946243, 1.89947759, 1.24373076, 1.90414391],
        [1.55585711, 1.61807061, 1.66423265, 1.82842348, 1.82924037]],

       [[1.80742628, 1.93194212, 1.49134654, 1.92310726, 1.93792914],
        [1.81802654, 1.23063904, 1.25591393, 1.2326182 , 1.26363679],
        [1.59413087, 1.55976807, 1.52913791, 1.05082046, 1.01794061]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [74]:
# your code/answer here
# relation a = d - c
print(a)

[[[0.78783247 0.40898748 0.33323612 0.17844396 0.73812431]
  [0.27620709 0.12946243 0.89947759 0.24373076 0.90414391]
  [0.55585711 0.61807061 0.66423265 0.82842348 0.82924037]]

 [[0.80742628 0.93194212 0.49134654 0.92310726 0.93792914]
  [0.81802654 0.23063904 0.25591393 0.2326182  0.26363679]
  [0.59413087 0.55976807 0.52913791 0.05082046 0.01794061]]]


In [75]:
print(d)

[[[1.78783247 1.40898748 1.33323612 1.17844396 1.73812431]
  [1.27620709 1.12946243 1.89947759 1.24373076 1.90414391]
  [1.55585711 1.61807061 1.66423265 1.82842348 1.82924037]]

 [[1.80742628 1.93194212 1.49134654 1.92310726 1.93792914]
  [1.81802654 1.23063904 1.25591393 1.2326182  1.26363679]
  [1.59413087 1.55976807 1.52913791 1.05082046 1.01794061]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [76]:
# your code here
e = np.multiply(a,c)
e

array([[[0.78783247, 0.40898748, 0.33323612, 0.17844396, 0.73812431],
        [0.27620709, 0.12946243, 0.89947759, 0.24373076, 0.90414391],
        [0.55585711, 0.61807061, 0.66423265, 0.82842348, 0.82924037]],

       [[0.80742628, 0.93194212, 0.49134654, 0.92310726, 0.93792914],
        [0.81802654, 0.23063904, 0.25591393, 0.2326182 , 0.26363679],
        [0.59413087, 0.55976807, 0.52913791, 0.05082046, 0.01794061]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [77]:
# your code/answer here
# yes since we multiply all values by 1, they remain identifical
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [78]:
# your code here
print(d)

[[[1.78783247 1.40898748 1.33323612 1.17844396 1.73812431]
  [1.27620709 1.12946243 1.89947759 1.24373076 1.90414391]
  [1.55585711 1.61807061 1.66423265 1.82842348 1.82924037]]

 [[1.80742628 1.93194212 1.49134654 1.92310726 1.93792914]
  [1.81802654 1.23063904 1.25591393 1.2326182  1.26363679]
  [1.59413087 1.55976807 1.52913791 1.05082046 1.01794061]]]


In [79]:
d_max = d.max()
d_max

1.9379291386769524

In [93]:
d_min = d.min()
d_min

1.0179406107323528

In [94]:
d_mean = d.mean()
d_max

1.9379291386769524

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [82]:
# your code here
f = np.empty((2,3,5))
print(f)

[[[1.78783247 1.40898748 1.33323612 1.17844396 1.73812431]
  [1.27620709 1.12946243 1.89947759 1.24373076 1.90414391]
  [1.55585711 1.61807061 1.66423265 1.82842348 1.82924037]]

 [[1.80742628 1.93194212 1.49134654 1.92310726 1.93792914]
  [1.81802654 1.23063904 1.25591393 1.2326182  1.26363679]
  [1.59413087 1.55976807 1.52913791 1.05082046 1.01794061]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [86]:
print(d) #2x3x5

[[[1.78783247 1.40898748 1.33323612 1.17844396 1.73812431]
  [1.27620709 1.12946243 1.89947759 1.24373076 1.90414391]
  [1.55585711 1.61807061 1.66423265 1.82842348 1.82924037]]

 [[1.80742628 1.93194212 1.49134654 1.92310726 1.93792914]
  [1.81802654 1.23063904 1.25591393 1.2326182  1.26363679]
  [1.59413087 1.55976807 1.52913791 1.05082046 1.01794061]]]


In [96]:
# your code here
for i in range (0,2):
    for j in range (0,3):
        for k in range (0,5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            else:
                f[i][j][k] = 100
print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  25.  75. 100.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.   0.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [97]:
# your code here
print(d)

[[[1.78783247 1.40898748 1.33323612 1.17844396 1.73812431]
  [1.27620709 1.12946243 1.89947759 1.24373076 1.90414391]
  [1.55585711 1.61807061 1.66423265 1.82842348 1.82924037]]

 [[1.80742628 1.93194212 1.49134654 1.92310726 1.93792914]
  [1.81802654 1.23063904 1.25591393 1.2326182  1.26363679]
  [1.59413087 1.55976807 1.52913791 1.05082046 1.01794061]]]


In [98]:
print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 75.  75.  25.  75. 100.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.   0.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [106]:
# your code here
f = [[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]]]
for i in range (0,2):
    for j in range (0,3):
        for k in range (0,5):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = "B"
            elif d[i][j][k] == d_mean:
                f[i][j][k] = "C"
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = "D"
            elif d[i][j][k] == d_min:
                f[i][j][k] = "A"
            else:
                f[i][j][k] = "E"
np.array(f)

array([[['D', 'B', 'B', 'B', 'D'],
        ['B', 'B', 'D', 'B', 'D'],
        ['D', 'D', 'D', 'D', 'D']],

       [['D', 'D', 'B', 'D', 'E'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'B', 'B', 'A']]], dtype='<U1')